name: Kinoite Custom - Latest
on:
  merge_group:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - '.github/workflows/cleanup*.yml'
      - '.github/workflows/*silverblue*.yml'
      - '**.md'
      - 'system_files/silverblue/**'
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/cleanup*.yml'
      - '.github/workflows/*silverblue*.yml'
      - '**.md'
      - 'system_files/silverblue/**'
  schedule:
    - cron: '40 4 * * *'  # 4:40 UTC everyday
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      base_name: kinoite
      image_version: latest

