name: Silverblue Stable
on:
  merge_group:
  pull_request:
    branches:
      - main
      - testing
    paths-ignore:
      - '.github/workflows/cleanup*.yml'
      - '**.md'
      - 'system_files/kinoite/**'
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/cleanup*.yml'
      - '**.md'
      - 'system_files/kinoite/**'
  schedule:
    - cron: '15 5 * * 2'  # 5:15 UTC everyday
  workflow_dispatch:

jobs:
  build:
    name: build
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      base_name: silverblue
      image_version: stable

